version: '3.3'

services:
  db:
    container_name: postgres
    image: postgres:12
    restart: always
    command: postgres -c 'max_connections=100'
    shm_size: 2g
    env_file: deploy/postgresql.env

  flask:
    build:
      context: .
      dockerfile: deploy/Dockerfile-dev
    volumes:
      - .:/code
    depends_on:
      - db
    command: flask run --host=0.0.0.0
    env_file: deploy/backend.env
    ports:
      - 5000:5000

  test:
    build:
      context: .
      dockerfile: deploy/Dockerfile-dev
    volumes:
      - .:/code
    depends_on:
      - db
    command: bash run_pytest.sh
    env_file: deploy/backend.env
